PROGNAME = my_game_name.tos

CC = cc68x
AS = gen
CD = cd
RM = Rm

CFLAGS= -I./
 
ASFLAGS = -D -L2

C_OBJ = \
file_one.o \
file_two.o

ASM_OBJ = \
asm_file_one.o \
asm_file_two.o

OBJ = $(C_OBJ) $(ASM_OBJ)

$(PROGNAME): $(OBJ)
	$(CC) -o $(PROGNAME) $(OBJ)

file_one.o: file_one.c
	$(CC) $(CFLAGS) -c $< -o $@
file_two.o: file_two.c
	$(CC) $(CFLAGS) -c $< -o $@

asm_file_one.o: asm_file_one.s
	$(AS) $(ASFLAGS) $< -o$@
asm_file_two.o: asm_file_two.s
	$(AS) $(ASFLAGS) $< -o$@

clean:
	!$(RM) $(PROGNAME) $(OBJ)
